import containerQueries from '@tailwindcss/container-queries';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx,vue,md,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container': '#ebeef4',
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#324575',
        'surface-container-high': '#e5e8ee',
        'surface-container-highest': '#dfe3e8',
        'tertiary-fixed-dim': '#ffb59b',
        'secondary-fixed-dim': '#b3c5fd',
        outline: '#737785',
        'outline-variant': '#c3c6d6',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#dae2ff',
        'on-secondary-fixed': '#001847',
        'primary-fixed': '#dae2ff',
        'secondary-container': '#b3c5fd',
        'error-container': '#ffdad6',
        'tertiary-container': '#a93802',
        'on-primary-container': '#ccd8ff',
        'surface-tint': '#0056d2',
        background: '#f7f9ff',
        'on-tertiary-container': '#ffcebd',
        'on-primary-fixed': '#001847',
        'on-surface-variant': '#424654',
        'on-surface': '#181c20',
        'surface-bright': '#f7f9ff',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        'on-tertiary-fixed-variant': '#812800',
        'on-secondary-container': '#3e5181',
        'surface-container-low': '#f1f4fa',
        'inverse-on-surface': '#eef1f7',
        'surface-dim': '#d7dae0',
        'tertiary-fixed': '#ffdbcf',
        'inverse-primary': '#b2c5ff',
        'on-secondary': '#ffffff',
        'primary-container': '#0056d2',
        'on-tertiary-fixed': '#380d00',
        'inverse-surface': '#2d3135',
        secondary: '#4a5d8e',
        primary: '#0040a1',
        'surface-container-lowest': '#ffffff',
        tertiary: '#822800',
        'on-primary-fixed-variant': '#0040a1',
        'surface-variant': '#dfe3e8',
        surface: '#f7f9ff',
        'primary-fixed-dim': '#b2c5ff',
        'on-background': '#181c20',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [forms, containerQueries],
};
